### ISSUE TITLE
Does not print all help items when importing commands

### ISSUE THREAD

**Issue by davidespo** [ranjithrd/lithium#1]
If you import commands from multiple files (exactly like the starter), the `help` command does not print all commands.

# Steps to Reproduce

1. Follow the exact steps in https://lithium.js.org/docs/starting#installing-via-the-npx-command
2. Run `lithium_starter help` from the command line

## Expected Results

```
lithium_starter help

   ┌──────────────────────────────────┐
   │                                  │
   │   Your New Project Starts Here   │
   │                                  │
   └──────────────────────────────────┘



help: Shows a list of all commands
greet:
bye:

Lithium -- A micro-framework for creating CLIs.
```

## Actual Results

Missing the `greet` command.

```
lithium_starter help

   ┌──────────────────────────────────┐
   │                                  │
   │   Your New Project Starts Here   │
   │                                  │
   └──────────────────────────────────┘



help: Shows a list of all commands
bye:

Lithium -- A micro-framework for creating CLIs.
```

**Comment by ranjithrd** [comment]
Thanks, @davidespo for opening this issue. I merged your PR and published it to NPM as well.
